[plugin]
repository = "https://github.com/UnknownX7/ARealmRecorded.git"
commit = "c238c69dee945ced5a18a1c997ba9384f2e57be4"
owners = [ "UnknownX7" ]
changelog = '''
- Fixed an issue with hiding your own name'''
